<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Identity_Auth_MicroService.Servives_Abstraction</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity(Auth)MicroService.Domain\Identity(Auth)MicroService.Domain.csproj" />
    <ProjectReference Include="..\Identity(Auth)MicroService.Shared\Identity(Auth)MicroService.Shared.csproj" />
  </ItemGroup>

</Project>
